### ISSUE TITLE
What is the suggested approach for building the NEXT.js app after services are running and accepting requests?

### ISSUE THREAD

**Issue by mbopp** [platformsh-templates/nextjs#11]
For a NEXT.js app that requires an API that is also serviced on the same platform instance, do I need to do all `build` activity in the post_deploy hook? Similar to how the platform.sh Gatsby templates work? Will there be an issue with writing the build artifacts during this hook/phase?

It would be ideal if there was a way to call the API before it becomes publicly available for requests, but I understand the complexity of this.  I'd like to follow any best practices for this particular scenario, as I assume it is a fairly common pattern. Building the app during the build phase is ideal, but not possible until the 'API' container is up and running.

Any advice would be greatly appreciated! Thanks

**Comment by chadwcarlson** [comment]
Another container in an environment will not be available until the deploy hook, but there is also no way to schedule the deployment of one container _before_ another during their respective deploy hooks. Because of this, yes, it is recommended that you

- build API app1 during its build hook
- deploy API app1 during its deploy hook
- Build NextJS app2 during its post_deploy hook

**Comment by mbopp** [comment]
Thanks @chadwcarlson. Referring to the 'template' `.app.platform.yaml` file in this project... Would the `handle_mounts.sh` script still be necessary? If I'm understanding correctly, that script is for taking advantage of the build phase for 'building' the site, and letting the deployment step just move them into place.  But TBH I'm not super clear.  You suggestion is, for the next.js app, move all the build processing into the post_deploy hook, correct?

**Comment by chadwcarlson** [comment]
Hey @mbopp - really gotta find out why I'm not getting these notifications. 

If we forget your use case for a minute, and just talk about building and deploying a NextJS application, the steps will go like this

- validate containers
- run build hook

then
- connect mounted directories
- run start command
- run build hook

Everything that happens in the first "build" block happens in a file system with write access. After that stage, everything is read-only, except for the mounts you define in `.platform.app.yaml`. 

Now, `handle_mounts.sh` is trying to handle this schedule. Specifically, let's say I have something committed in `.next` locally that I want to push up to Platform.sh, _but_ I also want to have write access to that directory at runtime. If I just define the mount, when it actually becomes available at deploy time it will shadow over that directory, making committed files in `.next` unavailable. 

So with the `handle_mounts.sh`, we check 1) if files exist in build in `.next`, copy them to a temp directory. 2) In deploy, if a temp directory exists, copy them back onto the mount. 

For your use case, you'll have to determine if its necessary to handle this write access/committed files balance in a similar way.

**Comment by mbopp** [comment]
Thanks @chadwcarlson. This is helpful in understanding the handle mounts functionality. Appreciate your explanation. I _think_ that, in our case, using the script to handle the `.next` directory isn't necessary... but also isn't hurting anything either. In any case, it's helpful to understand things more.
